apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-delp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: ewertao/k8s-django-app:latest
        envFrom:
        - secretRef:
            name: django-app-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

